# Generated by Django 3.0.8 on 2020-12-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_productfeatures_productfeaturevalidators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
