# Generated by Django 3.0.8 on 2020-12-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201202_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
