# Generated by Django 3.0.8 on 2021-01-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210105_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category1',
            field=models.ManyToManyField(to='mainapp.Category1'),
        ),
    ]
