# Generated by Django 3.0.8 on 2020-12-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201214_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='for_anonymoys_user',
        ),
    ]
