# Generated by Django 3.0.8 on 2021-01-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210105_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytopimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category1',
        ),
        migrations.AddField(
            model_name='mytopimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='TopImage', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='mytopimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='TopImage', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='myimage',
            name='imagedown1',
            field=models.ImageField(blank=True, null=True, upload_to='DownImage', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='myimage',
            name='imagedown2',
            field=models.ImageField(blank=True, null=True, upload_to='DownImage', verbose_name='Изображение 2'),
        ),
        migrations.DeleteModel(
            name='Category1',
        ),
    ]
