# Generated by Django 3.0.8 on 2020-12-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_cart_for_anonymoys_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymoys_user',
            field=models.BooleanField(default=False),
        ),
    ]
