# Generated by Django 3.0.8 on 2020-12-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201202_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
