# Generated by Django 3.0.8 on 2021-01-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210106_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changemyinfo',
            old_name='Adress1',
            new_name='adress1',
        ),
        migrations.RenameField(
            model_name='changemyinfo',
            old_name='Adress2',
            new_name='adress2',
        ),
        migrations.AddField(
            model_name='changemyinfo',
            name='phone1',
            field=models.CharField(default=1, max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changemyinfo',
            name='phone2',
            field=models.CharField(default=1, max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
