# Generated by Django 3.0.8 on 2021-01-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210106_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='changemyinfo',
            name='phone1',
            field=models.CharField(default=1, max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changemyinfo',
            name='phone2',
            field=models.CharField(default=1, max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
