# Generated by Django 3.0.8 on 2021-01-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210106_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='Емайл'),
        ),
    ]
