# Generated by Django 3.0.8 on 2020-12-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20201216_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='user',
        ),
    ]
