# Generated by Django 3.0.8 on 2021-01-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_order_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=150, null=True, verbose_name='Текст')),
                ('doptext', models.CharField(blank=True, max_length=700, null=True, verbose_name='Дополнительный Текст')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=150, null=True, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=150, null=True, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Logo', verbose_name='Логотип')),
                ('insta', models.URLField(blank=True, null=True, verbose_name='Инстаграмм')),
                ('twiter', models.URLField(blank=True, null=True, verbose_name='Твитер')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Фейсбук')),
            ],
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returns', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок')),
                ('returnsText', models.CharField(blank=True, max_length=700, null=True, verbose_name='Дополнительный Текст')),
            ],
        ),
        migrations.AlterField(
            model_name='changemyinfo',
            name='email2',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Емайл для адрес 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='+38-050-111-11-11', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
    ]
