# Generated by Django 3.0.8 on 2021-01-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210123_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Информация на странице о Нас', 'verbose_name_plural': 'Информация на странице о Нас'},
        ),
        migrations.AlterModelOptions(
            name='changemyinfo',
            options={'verbose_name': 'Изменить адрес', 'verbose_name_plural': 'Изменить адреса'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Информация на странице Контактов', 'verbose_name_plural': 'Информация на странице Контактов'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Информация на странице о Доставке', 'verbose_name_plural': 'Информация на странице о Доставке'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'логотип и  соц.сети', 'verbose_name_plural': 'логотип и  соц.сети'},
        ),
        migrations.AlterModelOptions(
            name='returns',
            options={'verbose_name': 'Информация на странице о Возврате', 'verbose_name_plural': 'Информация на странице о Возврате'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размеры', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.RemoveField(
            model_name='size',
            name='gender',
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(help_text='Выберите доступные размеры продукта', to='mainapp.Size', verbose_name='размеры'),
        ),
        migrations.AlterField(
            model_name='size',
            name='foot_size',
            field=models.CharField(max_length=50),
        ),
    ]
