# Generated by Django 3.0.8 on 2020-12-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20201217_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='session',
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self', 'Отделение'), ('delivery', 'Курьер')], default='self', max_length=100, verbose_name='Тип заказа'),
        ),
    ]
