# Generated by Django 3.0.8 on 2020-12-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20201217_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self', 'Отделение'), ('delivery', 'Курьер')], default='self', max_length=100, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен'), ('deactive', 'Заказ Отменен')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
