# Generated by Django 3.0.8 on 2021-01-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210123_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Размер'),
        ),
    ]
