# Generated by Django 3.0.8 on 2021-01-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_cartproduct_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='AboutImage/', verbose_name='Изображение '),
        ),
    ]
