# Generated by Django 3.0.8 on 2021-01-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_aboutus_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='doptext',
        ),
    ]
