# Generated by Django 3.0.8 on 2020-12-21 22:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_product_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
