# Generated by Django 3.0.8 on 2021-01-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_aboutus_doptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Текст'),
        ),
    ]
