# Generated by Django 3.0.8 on 2021-01-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20210124_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='insta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Инстаграмм'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон'),
        ),
    ]
