# Generated by Django 3.0.8 on 2020-12-21 22:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20201222_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
