# Generated by Django 3.0.8 on 2020-12-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20201222_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='characteristics',
            new_name='properties',
        ),
    ]
