# Generated by Django 3.0.8 on 2021-01-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20210124_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='text',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Текст'),
        ),
    ]
