# Generated by Django 3.0.8 on 2021-01-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20210124_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='text',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Текст'),
        ),
    ]
