# Generated by Django 3.0.8 on 2020-12-23 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20201222_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ProductTechInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='значение')),
                ('separator', models.BooleanField(default=False, verbose_name='заголовок?')),
                ('position', models.SmallIntegerField(default=999, verbose_name='позиция')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='mainapp.TechInfo', verbose_name='имя')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techinfo', to='mainapp.Product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'техническая информация',
                'verbose_name_plural': 'техническая информация',
                'ordering': ('position',),
            },
        ),
    ]
