# Generated by Django 3.0.8 on 2021-01-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20210124_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returns',
            name='returns',
        ),
        migrations.RemoveField(
            model_name='returns',
            name='returnsText',
        ),
        migrations.AddField(
            model_name='returns',
            name='text',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='returns',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
    ]
