# Generated by Django 3.0.8 on 2020-12-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_producttechinfo_techinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTechInfo',
        ),
        migrations.DeleteModel(
            name='TechInfo',
        ),
    ]
