# Generated by Django 3.0.8 on 2020-12-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20201224_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTopimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='myimage',
            name='imagetop1',
        ),
        migrations.RemoveField(
            model_name='myimage',
            name='imagetop2',
        ),
        migrations.RemoveField(
            model_name='myimage',
            name='title',
        ),
    ]
