# Generated by Django 3.0.8 on 2021-01-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20210124_1452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReturnItem',
            new_name='ReturnsItem',
        ),
    ]
