# Generated by Django 3.0.8 on 2020-12-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20201226_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytopimage',
            old_name='imgage',
            new_name='image',
        ),
    ]
