# Generated by Django 3.0.8 on 2020-12-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20201226_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='текст в бегущей строке')),
            ],
            options={
                'verbose_name': 'Изображение сверху',
                'verbose_name_plural': 'Изображения сверху',
            },
        ),
        migrations.AlterModelOptions(
            name='myimage',
            options={'verbose_name': 'Изображение снизу', 'verbose_name_plural': 'Изображения снизу'},
        ),
        migrations.AlterModelOptions(
            name='mytopimage',
            options={'verbose_name': 'Изображение сверху', 'verbose_name_plural': 'Изображения сверху'},
        ),
    ]
