# Generated by Django 3.0.8 on 2021-01-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_whishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlist',
            name='products',
        ),
        migrations.AddField(
            model_name='whishlist',
            name='products',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Продукты', to='mainapp.Product'),
            preserve_default=False,
        ),
    ]
