# Generated by Django 3.0.8 on 2020-12-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20201226_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toptext',
            options={'verbose_name': 'текст в бегущей строке'},
        ),
        migrations.AddField(
            model_name='toptext',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='toptext',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='текст в бегущей строке'),
        ),
    ]
