# Generated by Django 3.0.8 on 2020-12-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20201226_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytopimage',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
