# Generated by Django 3.0.8 on 2021-02-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Сылка на обзор с ЮТУБА если есть'),
        ),
    ]
