# Generated by Django 3.0.8 on 2021-02-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_remove_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('payment', 'Заказ оплачен'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен'), ('deactive', 'Заказ Отменен')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
