# Generated by Django 3.0.8 on 2021-02-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20210202_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_pay',
            field=models.CharField(choices=[('pay', 'Олачен'), ('not_pay', 'Отклонен'), ('miss', 'Ошибка при оплате'), ('nal', 'Наложенный платеж')], default='nal', max_length=100, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cпособ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен'), ('deactive', 'Заказ Отменен')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
