# Generated by Django 3.0.8 on 2021-02-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20210205_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_pay',
            field=models.CharField(choices=[('pay', 'Оплачен'), ('not_pay', 'Отклонен'), ('miss', 'Ошибка при оплате'), ('nal', 'Наложенный платеж'), ('wait', 'Ожидание платежа'), ('reversed', 'Платеж возвращен')], default='nal', max_length=100, verbose_name='Оплата'),
        ),
    ]
