# Generated by Django 3.0.8 on 2021-02-10 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Url категории')),
            ],
            options={
                'verbose_name': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Название тега')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Url слага')),
            ],
            options={
                'verbose_name': 'Теги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Url статьи')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Опубликовано')),
                ('photo', models.ImageField(blank=True, upload_to='blog/photos/%Y/%m/%d/')),
                ('views', models.IntegerField(default=0, verbose_name='Кол-во просотров')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.Tag')),
            ],
            options={
                'verbose_name': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
    ]
